---
title: "Github Issue Dashboard"
author: "Jimmy Briggs"
params:
  users: jimbrig
  orgs: 
    - jimbrig-work
    - tychobra
    - powwater
output: 
  flexdashboard::flex_dashboard
---

```{css}
a:link {
  color: black;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(reactable)
library(tidyverse)
library(glue)
library(gh)
library(emo)
library(htmltools)
library(farver)
library(stringr)

require(flexdashboard)
require(sass)
require(tidyr)
```

```{r repos}
user_repos <- purrr::map(params$users, function(x) {
  
  query <- paste0("/users/", x, "/repos")
  
  repos_out <- gh::gh(query, .limit = Inf) %>% 
    purrr::map_depth(1, purrr::pluck, "full_name") %>%
    purrr::map_chr(purrr::pluck, 1)
  
  repos_out
}) %>% purrr::flatten_chr()

org_repos <- purrr::map(params$orgs, function(x) {
  
  query <- paste0("/orgs/", x, "/repos")
  
  repos_out <- gh::gh(query, .limit = Inf) %>% 
    purrr::map_depth(1, purrr::pluck, "full_name") %>%
    purrr::map_chr(purrr::pluck, 1) %>%
    purrr::discard(stringr::str_detect, regex("[:digit:]"))
  
  repos_out
}) %>% purrr::flatten_chr()

repos <- c(user_repos, org_repos)
```

```{r parsing}
#' Read all issues from repositories
#'
#' @param repo Character vector of repositories in the format "owner/name".
#'
#' @return tibble with 1 row per issue.
all_issues <- function(repo) {
  map_dfr(repo, github_summary)
}

#' Read all issues from 1 repository
#'
#' @param repo Character of repository in the format "owner/name".
#'
#' @return tibble with 1 row per issue.
github_summary <- function(repo) {
  x <- gh(glue("/repos/{repo}/issues"))
  map_dfr(x, issue_summary) 
}

#' Extract relevant issue information
#'
#' @param repo Output from [gh::gh()]
#'
#' @return List with 7 elements.
issue_summary <- function(x) {
  list(
    repository = x$repository_url,
    title = x$title,
    issue_url = x$html_url,
    created_at = x$created_at,
    updated_at = x$updated_at,
    comments = x$comments,
    labels = list(x$labels)
  )
}
```

```{r, download}
# Download all issues
user_issues <- all_issues(user_repos) %>%
  # Combine issue_url and title
  mutate(title = glue('<a href="{issue_url}">{title}</a>')) %>%
  select(-issue_url)

org_issues <- all_issues(org_repos) %>%
  # Combine issue_url and title
  mutate(title = glue('<a href="{issue_url}">{title}</a>')) %>%
  select(-issue_url)
```

```{r, tidiers}
# Replaces github style emojies with emojies using [emo::ji]
substitute_emoji <- function(x) {
  m <- gregexpr(":[^[:space:]]+:", x)
  regmatches(x, m) <- lapply(regmatches(x, m), function(xx) map_chr(gsub(":", "", xx), emo::ji))
  x
}

# Turns date format into 2020-01-01 format
date_format <- function(value) {
  str_sub(value, 1, 10)
}

# Removes `api` and `repos` from Github url
remove_api_url <- function(x) {
  url <- str_remove(x, "api\\.")
  str_remove(url, "repos/")
}

# Extracts `owner/name` part from github url and create a tag with link to repository
extract_github_url <- function(value) {
  url <- remove_api_url(value)
  
  text <- str_remove(url, "https://github.com/")
  glue('<a href="{url}">{text}</a>')
}
```

```{r}
# Takes a color and returns white or black depending on what would be the best 
# text color for that background color
color_flip <- function(x) {
  x <- paste0("#", x)
  color_lightness <- farver::convert_colour(t(col2rgb(x)), "rgb", "hsl")[, "l"]
  ifelse(color_lightness > 31, "#010101", "#FFFFFF")
}

# Style 1 github issue label to look like label on Website
style_label <- function(x) {
  a(substitute_emoji(x$name), 
    href = remove_api_url(x$url), 
    style = glue("background: #{x$color};
                  padding: 0 7px;
                  color: {color_flip(x$color)};
                  text-decoration: none;
                  border-radius: 2em;"))
}

# Styles n labels and combine them in a span
style_labels <- function(x) {
  span(map(x, style_label))
}
```

PERSONAL
==============================================

```{r table_prep}
# filter out dependabot
user_issues_dependabot <- user_issues %>%
  dplyr::mutate(dependabot = purrr::map(.data$labels, ~purrr::pluck(.x, 1, "name"))) %>%
  dplyr::filter(.data$dependabot == "dependencies") %>%
  dplyr::select(-dependabot)

user_issues_out <- user_issues %>%
  anti_join(user_issues_dependabot)

user_issue_tbl <- user_issues_out %>%
  reactable(
    highlight = TRUE,
    searchable = TRUE,
    
    # Stopping long lines of text wrapping to keep table height consistent 
    wrap = FALSE,
    
    # Personally customized to fit my screen size and zoom level 
    defaultPageSize = 18,
    minRows = 18,
    
    # Sort table by such that most recently updated issue is at the top by default
    defaultSorted = "updated_at",
    defaultSortOrder = "desc",
    
    # Sets the searchbar to be 100% width
    theme = reactableTheme(
      searchInputStyle = list(width = "100%")
    ),
    
    # All columns have Custom Set Name
    # All but last column have pre-specified width set
    # Cell modification is done with functions
    # Columns which uses html formatting have `html = TRUE` to render html
    columns = list(
      title = colDef(
        name = "Title",
        width = 500,
        html = TRUE
        ),
      repository = colDef(
        name = "Repository",
        width = 250,
        cell = extract_github_url,
        html = TRUE,
        ),
      comments = colDef(
        name = "Comments",
        width = 100
        ),
      created_at = colDef(
        name = "Created",
        width = 120,
        cell = date_format, 
        filterable = FALSE
        ),
      updated_at = colDef(
        name = "Updated",
        width = 120,
        cell = date_format, 
        filterable = FALSE
        ),
      labels = colDef(
        name = "Labels",
        cell = style_labels,
        html = TRUE,
        filterable = FALSE
        )
      )
    )

user_dependabot_tbl <- user_issues_dependabot %>%
  reactable(
    highlight = TRUE,
    searchable = TRUE,
    
    # Stopping long lines of text wrapping to keep table height consistent 
    wrap = FALSE,
    
    # Personally customized to fit my screen size and zoom level 
    defaultPageSize = 18,
    minRows = 18,
    
    # Sort table by such that most recently updated issue is at the top by default
    defaultSorted = "updated_at",
    defaultSortOrder = "desc",
    
    # Sets the searchbar to be 100% width
    theme = reactableTheme(
      searchInputStyle = list(width = "100%")
    ),
    
    # All columns have Custom Set Name
    # All but last column have pre-specified width set
    # Cell modification is done with functions
    # Columns which uses html formatting have `html = TRUE` to render html
    columns = list(
      title = colDef(
        name = "Title",
        width = 500,
        html = TRUE
        ),
      repository = colDef(
        name = "Repository",
        width = 250,
        cell = extract_github_url,
        html = TRUE,
        ),
      comments = colDef(
        name = "Comments",
        width = 100
        ),
      created_at = colDef(
        name = "Created",
        width = 120,
        cell = date_format, 
        filterable = FALSE
        ),
      updated_at = colDef(
        name = "Updated",
        width = 120,
        cell = date_format, 
        filterable = FALSE
        ),
      labels = colDef(
        name = "Labels",
        cell = style_labels,
        html = TRUE,
        filterable = FALSE
        )
      )
    )
```

### User Issues - Excluding Dependabot

```{r user_issue_table}
user_issue_tbl
```

### User Issues - Dependabot

```{r user_dependabot_table}
user_dependabot_tbl
```

ORGANIZATIONS
==============================================

```{r}
org_issues %>%
  reactable(
    highlight = TRUE,
    searchable = TRUE,
    
    # Stopping long lines of text wrapping to keep table height consistent 
    wrap = FALSE,
    
    # Personally customized to fit my screen size and zoom level 
    defaultPageSize = 18,
    minRows = 18,
    
    # Sort table by such that most recently updated issue is at the top by default
    defaultSorted = "updated_at",
    defaultSortOrder = "desc",
    
    # Sets the searchbar to be 100% width
    theme = reactableTheme(
      searchInputStyle = list(width = "100%")
    ),
    
    # All columns have Custom Set Name
    # All but last column have pre-specified width set
    # Cell modification is done with functions
    # Columns which uses html formatting have `html = TRUE` to render html
    columns = list(
      title = colDef(
        name = "Title",
        width = 500,
        html = TRUE
        ),
      repository = colDef(
        name = "Repository",
        width = 250,
        cell = extract_github_url,
        html = TRUE,
        ),
      comments = colDef(
        name = "Comments",
        width = 100
        ),
      created_at = colDef(
        name = "Created",
        width = 120,
        cell = date_format, 
        filterable = FALSE
        ),
      updated_at = colDef(
        name = "Updated",
        width = 120,
        cell = date_format, 
        filterable = FALSE
        ),
      labels = colDef(
        name = "Labels",
        cell = style_labels,
        html = TRUE,
        filterable = FALSE
        )
      )
    )

```
